version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file: .env
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      timeout: 30s
      retries: 3

  app:
    depends_on:
      - postgres
    restart: on-failure
    build: .
    env_file: .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url" : "jdbc:postgresql://postgres_container:5432/${POSTGRES_DB}",
              "spring.datasource.username" : "${POSTGRES_USER}",
              "spring.datasource.password" : "${POSTGRES_PASSWORD}",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.datasource.driver-class-name" : "org.postgresql.Driver",
              "spring.jpa.hibernate.ddl-auto" : "validate"
            }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
